name: Puppeteer

on:
  repository_dispatch:
    types: test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci
    
    - name: Check for broken links
      id: link-report
      run: npm install broken-link-checker -g

    - name: Get the result
      run: blc https://www.google.com -efor
