name: Puppeteer

on:
  repository_dispatch:
    types: test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci
    
    - name: Test BCL
      uses: marccampbell/hugo-linkcheck-action@v0.1.3
      env:
        HUGO_FINAL_URL: https://www.google.com
