name: Puppeteer

on:
  repository_dispatch:
    types: regression

jobs:
  test1:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        device: ['desktop', 'mobile']
        tags: ['mobile', 'desktop']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Run test
      env:
        WEB_URL: https://www.google.com
      run: npm test

    - name: Write Test Result
      if: ${{ always() }}
      run: echo ${{ job.status }} > ${{ matrix.device }}.txt

    - name: Upload Test Result
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.device }}
        path: ${{ matrix.device }}.txt

  parallel:
    needs: [test1]
    if: ${{ always() }}

    runs-on: ubuntu-latest
  
    steps:
    - name: Download test results
      uses: actions/download-artifact@v1
      with:
        name: desktop
        
    - name: Download test results
      uses: actions/download-artifact@v1
      with:
        name: mobile
      
    - name: After parallel
      run: |
        echo ${{ desktop/desktop.txt }}
        echo ${{ mobile/mobile.txt }}
