name: Puppeteer

on:
  repository_dispatch:
    types: regression

jobs:
  test1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Run test
      env:
        WEB_URL: https://www.google.com
      run: npm test

  test2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Run test
      env:
        WEB_URL: https://www.google.com
      run: npm test

  parallel:
    needs: [test1, test2]
    if: ${{ always() }}

    runs-on: ubuntu-latest
  
    steps:
    - name: After parallel
      run: echo ${{ jobs.test1.status }}
